Classes/Testproject/Firstproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

Classes/Testproject/home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index,name="home"),
    path('register/', views.registerPage, name="register"),
    path('index', views.index,name="index"),
    path('about', views.about,name="about"),
    path('contact', views.contact,name="contact"),
    path('login', views.loginUser,name="login"),
    path('logout', views.logoutUser,name="logout"),
    path('blogform', views.blogform,name="blogform"),
    path('blogtag', views.blogform,name="blogtag"),
    path('blogtagsubmit', views.blogform,name="blogtagsubmit"),
    path('blogpost/<int:idd>', views.blogpost,name="blogpost"),
    path('blogpostdelete/<int:idd>', views.blogpostdelete,name="blogpostdelete"),
    path('blogpostupdate/<int:idd>', views.blogpostupdate,name="blogpostupdate"),
    path('blogajaxtest', views.ajaxTest,name="blogajaxtest"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Classes/Testproject/home/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=122)
    email=models.CharField(max_length=122)
    phone=models.CharField(max_length=122)
    desc=models.CharField(max_length=122)
    date=models.DateField()

class Tag(models.Model):
    title=models.CharField(max_length=56)

    def __str__(self):
        return self.title

class Blog(models.Model):
    title=models.CharField(max_length=122,null=True,default=None)
    desc=models.TextField(null=True,default=None)
    user_id=models.IntegerField(null=True,default=None)
    username=models.CharField(max_length=122,null=True,default=None)
    image=models.ImageField(upload_to='static/images/',null=True,default=None)
    date=models.DateField(null=True,default=None)
    tags=models.ManyToManyField(Tag,related_name='tagss',verbose_name="MyTags",null=True,default=None)
    # tags=models.ForeignKey(Tag,on_delete=models.CASCADE,verbose_name="My Tags",null=True,default=None)


class TESTADMIN(models.Model):
    name=models.CharField(max_length=122)
    email=models.CharField(max_length=122)
    phone=models.CharField(max_length=122)
    desc=models.CharField(max_length=122)
    date=models.DateField()

# class TempUser(models.Model):
#     first_name = models.CharField(max_length=100)
#     . . .
#     class Meta:
#         db_table = "temp_user"
    

Classes/Testproject/templates/about.html
{% extends 'base.html '%}

{% block title %}
About
{% endblock title%}

{% block body %}
This is about page
{% endblock body%}

Classes/Testproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %} {% endblock title%}</title>
  <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />
  <!-- Vendor CSS -->
  <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/vendor/vendor.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- Custom font -->
  <link href="{% static 'fonts/icomoon/icons.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Open%20Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  {% block style %} {% endblock style%}
</head>

<body class="has-smround-btns has-loader-bg equal-height has-sm-container">
 


    {% include 'navbar/navbar.html' %}


    {% block body %} {% endblock body%}


    {% include 'footer/footer.html' %}

  <script src="{% static 'js/vendor-special/lazysizes.min.js' %}"></script>
  <script src="{% static 'js/vendor-special/ls.bgset.min.js' %}"></script>
  <script src="{% static 'js/vendor-special/ls.aspectratio.min.js' %}"></script>
  <script src="{% static 'js/vendor-special/jquery.min.js' %}"></script>
  <script src="{% static 'js/vendor-special/jquery.ez-plus.js' %}"></script>
  <script src="{% static 'js/vendor/vendor.min.js' %}"></script>
  <script src="{% static 'js/app-html.js' %}"></script>
  {% block js %} {% endblock js %}
</body>

</html>

Classes/Testproject/templates/blogform.html
{% extends 'base.html '%}

{% block title %}
Blog Form
{% endblock title%}

{% block style %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock style %}

{% block body %}

{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{ message.tags }}" role="alert">
		{{ message }}
	</div>
	{% endfor %}
	{% endif %}

<div class="page-content">
    <div class="holder breadcrumbs-wrap mt-0">
      <div class="container">
        <ul class="breadcrumbs">
          <li><a href="index.html">Home</a></li>
          <li><span>Blog Form</span></li>
        </ul>
      </div>
    </div>
    <div class="holder">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-18 col-lg-12">
            <h2 class="text-center">Blog Form</h2>
            <div class="form-wrapper">
              <p>Please Fill information about your blog</p>
              <form action='/blogform' method='POST' enctype="multipart/form-data">
              {% csrf_token %}
                
                 
                    <div class="form-group">
                        {{form.title}}
                    </div>
                    <br>
                    <div class="form-group">
                        {{form.desc}}
                    </div>
                    <div class="form-group">
                        {{form.image}}
                    </div>
                    <div class="form-group">
                        {{form.date}}
                    </div>
                    <div class="form-group">
                      {{form.tags}}
                  </div>
                    
                    <div class="form-group">
                        {{form.username}}
                    </div>

                    <div class="form-group">
                      {{form.user_id}}
                  </div>
                    
                <div class="text-center">
                    <input type="submit" class="btn btn--sm" value="Submit">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#id_tags').select2();
  });
  </script>

  {% endblock %}

{% endblock body%}

Classes/Testproject/templates/blogformedit.html
{% extends 'base.html '%}

{% block title %}
Blog Form
{% endblock title%}

{% block style %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock style %}

{% block body %}

{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{ message.tags }}" role="alert">
		{{ message }}
	</div>
	{% endfor %}
	{% endif %}

<div class="page-content">
    <div class="holder breadcrumbs-wrap mt-0">
      <div class="container">
        <ul class="breadcrumbs">
          <li><a href="index.html">Home</a></li>
          <li><span>Blog Form</span></li>
        </ul>
      </div>
    </div>
    <div class="holder">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-18 col-lg-12">
            <h2 class="text-center">Blog Form</h2>
            <div class="form-wrapper">
              <p>Please Fill information about your blog</p>
              <form action='{% url 'blogpostupdate' id %}' method='POST' enctype="multipart/form-data">
              {% csrf_token %}
                
                    <div class="form-group">
                        {{form.title}}
                    </div>
                    <br>
                    <div class="form-group">
                        {{form.desc}}
                    </div>
                    <div class="form-group">
                        {{form.image}}
                    </div>
                    <div class="form-group">
                        {{form.date}}
                    </div>
                    <div class="form-group">
                      {{form.tags}}
                    </div>
                    <div class="form-group">
                        {{form.username}}
                    </div>
                    <div class="form-group">
                      {{form.user_id}}
                   </div>
                    
                <div class="text-center">
                    <input type="submit" class="btn btn--sm" value="Submit">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#id_tags').select2();
  });
  </script>

  {% endblock %}

{% endblock body%}

Classes/Testproject/templates/blogs.html
{% extends 'base.html '%}

{% block title %}
Test
{% endblock title%}

{% block body %}
{% load static %}
  
  <!--//header-->
  <div class="page-content">
    <div class="holder breadcrumbs-wrap mt-0">
      <div class="container">
        <ul class="breadcrumbs">
          <li><a href="index.html">Home</a></li>
          <li><span>Our Blog</span></li>
        </ul>
      </div>
    </div>
    <div class="holder">
      <div class="container">
        <div class="page-title text-center">
          <h1>Our Blog</h1>
        </div>
        <div class="row">
          <div class="col-md-14 aside aside--content">
            <div class="post-prws-listing">
              <div class="post-prw">
                <div class="row vert-margin-middle">
                  <div class="post-prw-img col-md-7">
                    <a href="blog-post.html">
                      <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="{% static 'images/blog/blog-01.png' %}" class="lazyload fade-up" alt="">
                    </a>
                  </div>
                  <div class="post-prw-text col-md-11">
                    <div class="post-prw-links">
                      <div class="post-prw-date"><i class="icon-calendar"></i>10 nov, 2020</div>
                      <div class="post-prw-date"><i class="icon-chat"></i>5 comments</div>
                    </div>
                    <h4 class="post-prw-title"><a href="blog-post.html">Home page visual builder</a></h4>
                    <div class="post-prw-teaser">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </div>
                    <div class="post-prw-btn">
                      <a href="blog-post.html" class="btn btn--sm">Read More</a>
                    </div>
                  </div>
                </div>
              </div>
              
            </div>
            <div class="pagination-wrap d-flex mt-4">
              <ul class="pagination mt-0">
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4 aside aside--sidebar aside--right">
            <div class="aside-content">
              <div class="aside-block">
                <h2 class="text-uppercase">Popular Tags</h2>
                <ul class="tags-list">
                  <li><a href="#">jeans</a></li>
                  <li><a href="#">hand bags</a></li>
                  <li><a href="#">gift card</a></li>
                  <li><a href="#">goodwin</a></li>
                  <li><a href="#">seiko</a></li>
                  <li><a href="#">banita</a></li>
                  <li><a href="#">foxic</a></li>
                </ul>
              </div>
              <div class="aside-block">
                <h2 class="text-uppercase">Popular Posts</h2>
                <div class="post-prw-simple-sm">
                  <a href="blog-post.html" class="post-prw-img">
                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="images/blog/blog-05.png" class="lazyload fade-up" alt="">
                  </a>
                  <div class="post-prw-links">
                    <div class="post-prw-date"><i class="icon-calendar"></i>August 27, 2020</div>
                    <a href="#" class="post-prw-author">by Jon Cock</a>
                  </div>
                  <h4 class="post-prw-title"><a href="#">FOXic shopify theme</a></h4>
                  <a href="#" class="post-prw-comments"><i class="icon-chat"></i>15 comments</a>
                </div>
              </div>
              <div class="aside-block">
                <h2 class="text-uppercase">Meta</h2>
                <ul class="list list--nomarker">
                  <li><a href="#">Log in</a></li>
                  <li><a href="#">Entries RSS</a></li>
                  <li><a href="#">Comments RSS</a></li>
                </ul>
              </div>
              <div class="aside-block">
                <h2 class="text-uppercase">Archives</h2>
                <ul class="list list--nomarker">
                  <li><a href="#">January 2018</a></li>
                  <li><a href="#">February 2018</a></li>
                  <li><a href="#">March 2018</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  {% endblock body%}

Classes/Testproject/templates/blogtag.html
{% extends 'base.html '%}

{% block title %}
Blog Form
{% endblock title%}

{% block style %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock style %}

{% block body %}

<div class="page-content">
    <div class="holder breadcrumbs-wrap mt-0">
      <div class="container">
        <ul class="breadcrumbs">
          <li><a href="index.html">Home</a></li>
          <li><span>Blog Form</span></li>
        </ul>
      </div>
    </div>
    <div class="holder">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-18 col-lg-12">
            <h2 class="text-center">Blog Form</h2>
            <div class="form-wrapper">
              <p>Please Fill information about your blog</p>
              <form action='/blogtagsubmit' method='POST' enctype="multipart/form-data">
              {% csrf_token %}
                
                    <div class="form-group">
                        {{form.title}}
                    </div>
                    <br>
                    
                <div class="text-center">
                    <input type="submit" value="Submit">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#id_tags').select2();
  });
  </script>

  {% endblock %}

{% endblock body%}

Classes/Testproject/templates/blogtagslist.html
{% extends 'base.html '%}

{% block title %}
Blog Form
{% endblock title%}

{% block style %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock style %}

{% block body %}

<div class="page-content">
    <div class="holder breadcrumbs-wrap mt-0">
      <div class="container">
        <ul class="breadcrumbs">
          <li><a href="index.html">Home</a></li>
          <li><span>Blog Form</span></li>
        </ul>
      </div>
    </div>
    <div class="holder">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-18 col-lg-12">
            <h2 class="text-center">Blog Form</h2>
            <a href="{% url 'blogtag' %}" class="btn btn--sm" style="float:right;">Create Tags</a>
            <div class="form-wrapper">
              <p>Please Fill information about your blog</p>
              



            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#id_tags').select2();
  });
  </script>

  {% endblock %}

{% endblock body%}

Classes/Testproject/templates/contact.html
{% block title %}
Contact
{% endblock title%}

{% block body %}

<div class ="container">
<form action="/contact" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name">Name</label><br>
    <input type="text" id="name" name="name"><br>
    <label for="phone">Phone</label><br>
    <input type="text" id="phone" name="phone"><br><br>
    <label for="email">Email</label><br>
    <input type="text" id="email" name="email"><br><br>
    <label for="desc">Description</label><br>
    <input type="text" id="desc" name="desc"><br><br>
    <input type="submit" value="Submit">
</form> 
</div>

{% endblock body%}

Classes/Testproject/templates/index.html
{% extends 'base.html '%}

{% block title %}
Test
{% endblock title%}

{% block body %}
{% load static %}

<div class="page-content">
  <div class="holder breadcrumbs-wrap mt-0">
    <div class="container">
      <ul class="breadcrumbs">
        <li><a href="index.html">Home</a></li>
        <li><span>Our Blog</span></li>
      </ul>
    </div>
  </div>
  <div class="holder">
    <div class="container">
      <div class="page-title text-center">
        <h1>Our Blog</h1>
        <a href="{% url 'blogform' %}" class="btn btn--sm" style="float:right;">Create Blog</a>
        <a href="{% url 'blogtag' %}" class="btn btn--sm" style="float:right;">Create Tags</a>
      </div>
      <br>
      <br>
      <br>
      <div class="row">
        
        <div class="col-md-14 aside aside--content">
          <div class="post-prws-listing">

            {% for blog in blogs %}
            <div class="post-prw">
              <div class="row vert-margin-middle">
                <div class="post-prw-img col-md-7">
                  <a href="{% url 'blogpost' blog.id %}">
                    <img src="{{blog.image}}" data-src="{{blog.image}}" class="lazyload fade-up" alt="">
                  </a>
                </div>
                <div class="post-prw-text col-md-11">
                  <div class="post-prw-links">
                    <div class="post-prw-date"><i class="icon-calendar"></i>10 nov, 2020</div>
                    <div class="post-prw-date"><i class="icon-chat"></i>5 comments</div>
                  </div>
                  <h4 class="post-prw-title"><a href="{% url 'blogpost' blog.id %}">{{blog.title}}</a></h4>
                  <div class="post-prw-teaser">{{blog.desc}}</div>
                  <div class="post-prw-btn">
                    <a href="{% url 'blogpost' blog.id %}" class="btn btn--sm">Read More</a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            
          </div>
          
          <div class="pagination-wrap d-flex mt-4">
            {% if blogs.has_other_pages %}
            <ul class="pagination mt-0">
              {% if blogs.has_previous %}
                <li><a href="?page={{ blogs.previous_page_number }}">&laquo;</a></li>
              {% else %}
                <li class="disabled"><span>&laquo;</span></li>
              {% endif %}
              {% for i in blogs.paginator.page_range %}
                {% if blogs.number == i %}
                  <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                  <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
              {% if blogs.has_next %}
                <li><a href="?page={{ blogs.next_page_number }}">&raquo;</a></li>
              {% else %}
                <li class="disabled"><span>&raquo;</span></li>
              {% endif %}
            </ul>
            {% endif %}
          </div>
        </div>
        <div class="col-md-4 aside aside--sidebar aside--right">
          <div class="aside-content">
            <div class="aside-block">
              <h2 class="text-uppercase">Popular Tags</h2>
              <ul class="tags-list">
                <li><a href="#">jeans</a></li>
                <li><a href="#">hand bags</a></li>
                <li><a href="#">gift card</a></li>
                <li><a href="#">goodwin</a></li>
                <li><a href="#">seiko</a></li>
                <li><a href="#">banita</a></li>
                <li><a href="#">foxic</a></li>
              </ul>
            </div>
            <div class="aside-block">
              <h2 class="text-uppercase">Popular Posts</h2>
              <div class="post-prw-simple-sm">
                <a href="blog-post.html" class="post-prw-img">
                  <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="images/blog/blog-05.png" class="lazyload fade-up" alt="">
                </a>
                <div class="post-prw-links">
                  <div class="post-prw-date"><i class="icon-calendar"></i>August 27, 2020</div>
                  <a href="#" class="post-prw-author">by Jon Cock</a>
                </div>
                <h4 class="post-prw-title"><a href="#">FOXic shopify theme</a></h4>
                <a href="#" class="post-prw-comments"><i class="icon-chat"></i>15 comments</a>
              </div>
            </div>
            <div class="aside-block">
              <h2 class="text-uppercase">Meta</h2>
              <ul class="list list--nomarker">
                <li><a href="#">Log in</a></li>
                <li><a href="#">Entries RSS</a></li>
                <li><a href="#">Comments RSS</a></li>
              </ul>
            </div>
            <div class="aside-block">
              <h2 class="text-uppercase">Archives</h2>
              <ul class="list list--nomarker">
                <li><a href="#">January 2018</a></li>
                <li><a href="#">February 2018</a></li>
                <li><a href="#">March 2018</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock body%}

Classes/Testproject/templates/login.html
{% extends 'base.html '%}

{% block title %}
Login
{% endblock title%}

{% block style %}
.divider:after,
.divider:before {
  content: "";
  flex: 1;
  height: 1px;
  background: #eee;
}
.h-custom {
  height: calc(100% - 73px);
}
@media (max-width: 450px) {
  .h-custom {
    height: 100%;
  }
}
{% endblock style%}

{% block body %}
<section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid"
            alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form action="/login" method="POST">
            {% csrf_token %}
            <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
              <p class="lead fw-normal mb-0 me-3">Sign in with</p>
              <button type="button" class="btn btn-primary btn-floating mx-1">
                <i class="fab fa-facebook-f"></i>
              </button>
  
              <button type="button" class="btn btn-primary btn-floating mx-1">
                <i class="fab fa-twitter"></i>
              </button>
  
              <button type="button" class="btn btn-primary btn-floating mx-1">
                <i class="fab fa-linkedin-in"></i>
              </button>
            </div>
  
            <div class="divider d-flex align-items-center my-4">
              <p class="text-center fw-bold mx-3 mb-0">Or</p>
            </div>
  
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" id="form3Example3" class="form-control form-control-lg"
                placeholder="Enter a valid email address" name="username" />
              <label class="form-label" for="form3Example3">Username</label>
            </div>
  
            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password" id="form3Example4" class="form-control form-control-lg"
                placeholder="Enter password" name="password"/>
              <label class="form-label" for="form3Example4">Password</label>
            </div>
  
            <div class="d-flex justify-content-between align-items-center">
              {% comment %} <!-- Checkbox -->
              <div class="form-check mb-0">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                <label class="form-check-label" for="form2Example3">
                  Remember me
                </label>
              </div>
              <a href="#!" class="text-body">Forgot password?</a> {% endcomment %}
            </div>
  
            <div class="text-center text-lg-start mt-4 pt-2">
              <button type="submit" class="btn btn-primary btn-lg"
                style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
              {% comment %} <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="#!"
                  class="link-danger">Register</a></p> {% endcomment %}
            </div>
  
          </form>
        </div>
      </div>
    </div>
    <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
      <!-- Copyright -->
      <div class="text-white mb-3 mb-md-0">
        Copyright © 2020. All rights reserved.
      </div>
      <!-- Copyright -->
  
      <!-- Right -->
      <div>
        <a href="#!" class="text-white me-4">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#!" class="text-white me-4">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#!" class="text-white me-4">
          <i class="fab fa-google"></i>
        </a>
        <a href="#!" class="text-white">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </div>
      <!-- Right -->
    </div>
  </section>
{% endblock body%}

Classes/Testproject/templates/test.html
<div class="page-content">
    <div class="holder breadcrumbs-wrap mt-0">
      <div class="container">
        <ul class="breadcrumbs">
          <li><a href="index.html">Home</a></li>
          <li><span>Create account</span></li>
        </ul>
      </div>
    </div>
    <div class="holder">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-18 col-lg-12">
            <h2 class="text-center">Create an Account</h2>
            <div class="form-wrapper">
              <p>To access your whishlist, address book and contact preferences and to take advantage of our speedy checkout, create an account with us now.</p>
              <form action="#">
                <div class="row">
                  <div class="col-sm-9">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="First name">
                    </div>
                  </div>
                  <div class="col-sm-9">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Last name">
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="E-mail">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control" placeholder="Password">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control" placeholder="Confirm Password">
                </div>
                <div class="clearfix">
                  <input id="checkbox1" name="checkbox1" type="checkbox" checked="checked">
                  <label for="checkbox1">By registering your details you agree to our <a href="#" class="custom-color" data-fancybox data-src="#modalTerms">Terms and Conditions</a> and <a href="#" class="custom-color" data-fancybox data-src="#modalCookies">Cookie Policy</a></label>
                </div>
                <div class="text-center">
                  <button class="btn">create an account</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  